### ISSUE TITLE
NotImplementedError: Platform does not define a GLUT font retrieval function

### ISSUE THREAD

**Issue by aquiles300** [Patrick-Cole/pygmi#15]
Hello Patrick

pygmi looks greats, but I am having problems when I kick off it in my linux.  In detail, I get 

(pygmi) [marcel@fedora pygmi-3.2.6.0]$ python quickstart.py 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/marcel/pygmi/pygmi-3.2.6.0/quickstart.py", line 47, in <module>
    main(nocgs=nocgs)
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/main.py", line 1312, in main
    wid = MainWidget(nocgs=nocgs)
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/main.py", line 621, in __init__
    menuimports.append(importlib.import_module(i))
  File "/home/marcel/.conda/envs/pygmi/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/pfmod/menu.py", line 29, in <module>
    from pygmi.pfmod import pfmod
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/pfmod/pfmod.py", line 34, in <module>
    from pygmi.pfmod import iodefs
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/pfmod/iodefs.py", line 40, in <module>
    from pygmi.pfmod import mvis3d
  File "/home/marcel/pygmi/pygmi-3.2.6.0/pygmi/pfmod/mvis3d.py", line 40, in <module>
    from OpenGL import GLUT
  File "/home/marcel/.conda/envs/pygmi/lib/python3.10/site-packages/OpenGL/GLUT/__init__.py", line 5, in <module>
    from OpenGL.GLUT.fonts import *
  File "/home/marcel/.conda/envs/pygmi/lib/python3.10/site-packages/OpenGL/GLUT/fonts.py", line 20, in <module>
    p = platform.getGLUTFontPointer( name )
  File "/home/marcel/.conda/envs/pygmi/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 350, in getGLUTFontPointer
    raise NotImplementedError( 
NotImplementedError: Platform does not define a GLUT font retrieval function

Can you help me to understand why it is not working?

Marcel

**Comment by Patrick-Cole** [comment]
Hi Marcel,

I think this is a linux issue. Have you tried the following?

$ sudo apt-get install libosmesa6
$ export PYOPENGL_PLATFORM=osmesa

If that does not work, please let me know the version of fedora and python you are using so I can try to duplicate it on my side.

**Comment by aquiles300** [comment]
Hi Patrick

It worked. Thank so much

Marcel

**Comment by Patrick-Cole** [comment]
Hi,

I am glad to hear that.

Patrick
